POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "kevin3",
    "password": "123"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "kevin",
    "password": "123"
}

###

GET http://localhost:5000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM0YmY1NDU0YjQyYjI4ZDQ3ODk2M2IiLCJpYXQiOjE2MjM1Njk3ODN9.hDdI1m7MLS9MzqE2_Grlbqg_R2wC55jdAOIgQbj9KmE


###
POST http://localhost:5000/api/movies/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM0YmY1NDU0YjQyYjI4ZDQ3ODk2M2IiLCJpYXQiOjE2MjM4MTE4MTF9.wQdSF4i5bwcxWx07kICbV7jNu29ysi2rsC_hjZt9GQM

{
    "name": "osdsdk",
    "des": "loldsdds",
    "image": "osdsjosd",
    "video": "dajncn"
}

###

GET http://localhost:5000/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM0YmY1NDU0YjQyYjI4ZDQ3ODk2M2IiLCJpYXQiOjE2MjM4MTE4MTF9.wQdSF4i5bwcxWx07kICbV7jNu29ysi2rsC_hjZt9GQM

###

PUT http://localhost:5000/api/movies/update/60c971b7015d2136b0bb746f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM0YmY1NDU0YjQyYjI4ZDQ3ODk2M2IiLCJpYXQiOjE2MjM4MTE4MTF9.wQdSF4i5bwcxWx07kICbV7jNu29ysi2rsC_hjZt9GQM

{
    "name": "Những Cô Gái Cute Cực Xinh Và Dễ Thương Triệu View Trên Tik Tok Việt Nam p20",
    "des": "Những Cô Gái Cute Cực Xinh Và Dễ Thương Triệu View Trên Tik Tok Việt Nam p20",
    "image": "F27sXBcOB3c",
    "video": "F27sXBcOB3c"
}

###

DELETE http://localhost:5000/api/movies/destroy/60c9745149609e0744599d2c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM0YmY1NDU0YjQyYjI4ZDQ3ODk2M2IiLCJpYXQiOjE2MjM4MTE4MTF9.wQdSF4i5bwcxWx07kICbV7jNu29ysi2rsC_hjZt9GQM